apiVersion: v1
kind: Service
metadata:
  name: seq-balancer
  namespace: k8s-test
spec:
  selector:
    app: seq
  ports:
    - name: seq-port
      protocol: TCP
      port: 5341
      targetPort: 80
  type: LoadBalancer