apiVersion: v1
kind: Service
metadata:
  name: sql-server-balancer
spec:
  selector:
    app: sql-server
  ports:
    - name: sql-server-port
      protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer