apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  namespace: k8s-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: notilya4/k8s-test.service
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: k8s